name: waste_sorter_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^14.2.7

  # State Management
  flutter_riverpod: ^2.5.1

  # UI Components
  flutter_svg: ^2.0.10+1

  # Location & Permissions
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # Camera
  camera: ^0.11.0+2
  image_picker: ^1.1.2

  # Storage
  shared_preferences: ^2.3.2

  # HTTP requests
  http: ^1.2.2

  # Firebase
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_storage: ^12.3.6

  # Utilities
  path: ^1.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icons/
    - assets/images/