// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAck-0TCFpNGrSKCQKHGScyYdataonAas8',
    appId: '1:251669996098:web:b66e21a51e681754dfc3db',
    messagingSenderId: '251669996098',
    projectId: 'waste-sorter-7f046',
    authDomain: 'waste-sorter-7f046.firebaseapp.com',
    storageBucket: 'waste-sorter-7f046.firebasestorage.app',
    measurementId: 'G-NM12J1R964',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI7YuMYMEhwlc7upYD8PFc9ID6hTR6pHk',
    appId: '1:251669996098:android:e48b58b6db8cadf0dfc3db',
    messagingSenderId: '251669996098',
    projectId: 'waste-sorter-7f046',
    storageBucket: 'waste-sorter-7f046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZYd1vOWQ90Ere-dEG9LnbyRWCzYhX_ZE',
    appId: '1:251669996098:ios:9210e481425a1fa4dfc3db',
    messagingSenderId: '251669996098',
    projectId: 'waste-sorter-7f046',
    storageBucket: 'waste-sorter-7f046.firebasestorage.app',
    iosClientId: '251669996098-iq4hpcu9bot07v0dvkg2s91mmuckpmj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteSorterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZYd1vOWQ90Ere-dEG9LnbyRWCzYhX_ZE',
    appId: '1:251669996098:ios:9210e481425a1fa4dfc3db',
    messagingSenderId: '251669996098',
    projectId: 'waste-sorter-7f046',
    storageBucket: 'waste-sorter-7f046.firebasestorage.app',
    iosClientId: '251669996098-iq4hpcu9bot07v0dvkg2s91mmuckpmj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteSorterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAck-0TCFpNGrSKCQKHGScyYdataonAas8',
    appId: '1:251669996098:web:f145b0cfe0ba35c5dfc3db',
    messagingSenderId: '251669996098',
    projectId: 'waste-sorter-7f046',
    authDomain: 'waste-sorter-7f046.firebaseapp.com',
    storageBucket: 'waste-sorter-7f046.firebasestorage.app',
    measurementId: 'G-BY3G3RZPNH',
  );
}
